### ISSUE TITLE
Recursion overflow

### ISSUE THREAD

**Issue by heartoneto** [georust/geo#1054] opened 2023-08-10 11:40 UTC
I'm getting this error while building my project with --release using geo-types = "0.7.11":

error[E0275]: overflow evaluating the requirement `[closure@/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/geo-0.23.1/src/algorithm/map_coords.rs:855:69: 855:72]: Fn<(geo_types::Coord<T>,)>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`geo`)
  = note: required for `&[closure@/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/geo-0.23.1/src/algorithm/map_coords.rs:855:69: 855:72]` to implement `Fn<(geo_types::Coord<T>,)>`
  = note: 128 redundant requirements hidden
  = note: required for `&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&...` to implement `Fn<(geo_types::Coord<T>,)>`
  = note: the full type name has been written to '/root/target/release/deps/geo-6ba1002ed94e92e9.long-type-9270678575324839979.txt'

For more information about this error, try `rustc --explain E0275`.
error: could not compile `geo` (lib) due to previous error

**Comment by lnicola** [comment] 2023-08-10 11:54
Duplicate of #1010. I suggest upgrading to a newer version of `geo` (the earliest one without the offending code is 0.25.0).

**Closed** 2023-08-12 01:01 UTC
