### ISSUE TITLE
Provide `WalkCoords` trait

### ISSUE THREAD

**Issue by rmanoka** [georust/geo#508] opened 2020-09-07 22:11 UTC
We currently have the very useful `MapCoords` and related traits.  However, it would be nice to have some similar equivalent of reducing / walking over the coordinates.  The simplest examples I can think of  is to simply compute the min and/or max coords of any of the geometry types.

**Comment by urschrei** [comment] 2020-09-07 22:53
This sounds like a better version of ExtremeIndices, which was intended to be an implementation of PolyMax2D from http://geomalgorithms.com/a14-_extreme_pts.html

**Comment by rmanoka** [comment] 2020-09-08 05:30
Yes, extremes.rs use case is what led me to this.  If we could provide a trait like this:

```rust
pub trait ForEachCoord {
    type Scalar: CoordinateType;
    fn for_each_coord<F: FnMut(Coordinate<Self::Scalar>)>(&self, f: F);
}
```

Then, impl of `ExtremePoint`, and also `ConvexHull` can be simplified.  The binary search that @urschrei linked above could be provided as a standalone algo that the can be used if the user knows that the `LineString` is convex.  Checking convexity in the impl. would lose all the time-complexity benefits unfortunately.

**Comment by rmanoka** [comment] 2020-09-09 06:52
A couple of discussion points:

1.  One interesting case is `Rect`.  Do we iterate over all 4 corners, or only the `min` and `max`?  For the applications we have in mind (ConvexHull, ExtremePoint), we should go over all 4 corners, but then how do we define the semantics of this trait?

1. Should we provide an early-exit method?  May be the function should be FnMut(Coordinate<T>) -> bool ?  If it returns false, we stop the iteration.   Ideally, this trait should just allow creating an appropriate iterator, but current stable rust doesn't make it easy to create such a trait.

**Comment by frewsxcv** [comment] 2020-09-14 13:11
Some prior art:

- I opened [a pull request](https://github.com/georust/geo/pull/164) a few years ago for a `CoordsIter` trait, but I forgot why I never merged it
- I experimented with an `ExteriorCoordsIterator` in [this pull request](https://github.com/georust/geo/pull/475/files#diff-fe6422ab9ac331f5d35bdd4bd64439e0R1-R47)

**Comment by frewsxcv** [comment] 2020-09-14 13:16
> On a side note:  why do MapCoords and family take a function `(T, T) -> (S, S)`, wouldn't it be more natural to be `Coordinate<T> -> Coordinate<S>`?   MapCoordsInplace would in particular be much simpler: just give a reference to the actual coordinate itself.

Agreed. My preference is to avoid using tuples to represent coordinates, since we have a `Coordinate` type.

**Comment by michaelkirk** [comment] 2020-11-14 06:34
My expectation and preference would be that the signatures would look something like:

```
geom.coords_iter() -> impl Iterator<Item = &Coordinate>
geom.coords_iter_mut() -> impl Iterator<Item = &mut Coordinate>
```

Then mapping would be:
```
geom.coords_iter().map(|coord: &Coordinate| do_something(coord));
```

And mutating:
```
geom.coords_iter_mut()(|coord: &Coordinate| do_something_mutating(coord));
```

Is there a reason to prefer the function param? It seems less composable and idiomatic than returning an iterator.

**Comment by michaelkirk** [comment] 2020-11-14 06:39
> I opened a pull request a few years ago for a CoordsIter trait, but I forgot why I never merged it

https://github.com/georust/geo/pull/164

lol.  I just looked at this and it's exactly what I was envisioning. Can we revive it? =)

**Comment by frewsxcv** [comment] 2020-11-16 21:55
Reopened #164 and it's ready for review

**Comment by frewsxcv** [comment] 2020-12-15 16:11
This was done in #164

**Closed by frewsxcv** 2020-12-15 16:11 UTC
Labels: enhancement
