### ISSUE TITLE
panic when computing centroid of some degenerate geometries

### ISSUE THREAD

**Issue by michaelkirk** [georust/geo#652] opened 2021-07-16 01:34 UTC
from https://github.com/georust/geo/pull/651#issuecomment-880768328

> [LineString and Polygon] both panic if a centroid can't be calculated. For instance, this code produces a panic:
>
> ```
> let empty_polygon: Polygon<f64> = polygon![];
> let rotated_empty_polygon = empty_polygon.rotate(90.);
> ```

Probably they should return a `None` centroid instead of exploding.

**Comment by mapoulos** [comment] 2021-07-16 01:58
I'll take a look.

**Comment by mapoulos** [comment] 2021-07-16 17:27
So for #651 we just returned a clone of the un-centroid-able multipolygon instead of changing the function signature.

Should we take the (probably more correct path) of making `rotate()` return an Option for each type (Polygon, Multipolygon, and LineString), which would require updating all the tests (and I guess bumping the minor version), or take the less invasive approach of returning a clone of an un-centroid-able geometry?

**Comment by michaelkirk** [comment] 2021-07-16 17:46
Honestly, I'm not sure. Degenerate geometries are always tricky.

We want to avoid Optional / Failable operations where possible, but not at the expense of "papering over errors".

For at least the case of empty geometries, even though it has no centroid, I think it's defensible to return an identical empty geometry, rather than None / error.

Are there inputs that are less defensible?

**Comment by mapoulos** [comment] 2021-07-17 20:39
The centroid test suite looks like it documents the expected behavior fairly well for degenerate geometries. It looks to me like empty geometries are the primary place a `None` is expected.  I'll look more closely to see if there are other degenerate geometries that will return `None` for a centroid, but a cursory glance suggests that we'd be safe to return a clone of the `geometry` in the case of no centroid

**Comment by michaelkirk** [comment] 2021-07-19 16:51
So, I think we agree that it's desirable:

- empty geometries should return a `None` centroid rather than panic
- rotating an empty geometry should return an indistinguishable empty geometry.

**Comment by lnicola** [comment] 2021-07-19 17:08
Mostly unrelated, but would it make sense to have a `rotate_in_place` method?

**Comment by mapoulos** [comment] 2021-07-21 18:48
a note, mostly to myself: check what happens if an infinite value is assigned to a point in a geometry.

**Comment by lnicola** [comment] 2021-07-21 18:51
Does it return a point with infinity as one of the coordinates? Maybe there's something in JTS about that.

**Comment by michaelkirk** [comment] 2021-07-26 23:21
> Does it return a point with infinity as one of the coordinates? Maybe there's something in JTS about that.

From what I can tell, JTS has no particular handling for infinity/NaN's, so normal floating point coalescing occurs: 
https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/algorithm/Centroid.java#L145

**Closed** 2021-07-27 18:35 UTC
